server:
  port: 8083
spring:
  application:
    name: consumer
  cloud:
    function:
      definition: consumer
    stream:
      kafka:
        bindings:
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
                spring:
                  json:
                    trusted.packages: '*'
      bindings:
        consumer-in-0:
          destination: test
          consumer:
            use-native-decoding: true
