variable:
    profile: dev
    binding-name: producer-out-0
    mock:
        base-url: http://localhost:8084
    keycloak:
        base-url: http://localhost:8080
        realm-name: test-realm
        client-id: mock-client
        client-secret: kjFCjCCJzARVJQjbYT6vfMupisVwiFRK
        username: consumer-service
        password: password
        access-url: http://localhost:8080/realms/${variable.keycloak.realm-name}/protocol/openid-connect/token
    