variable:
  db:
    page-size: 10
  kafka:
    producer:
      binding-name: consumer-in-0
server:
    port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/consumerDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  cloud:
    function:
      definition: consumer
    stream:
      bindings:
        consumer-in-0:
            destination: test-product