variable:
  bindingName: producer-out-0
server:
  port: 8081
spring:
  profiles:
    active:
    - dev
  application:
    name: consumer
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    function:
      definition: producer
    stream:
      bindings:
        producer-out-0:
          destination: test
          producer:
            useNativeEncoding: true