variable:
  retry:
    delay: 1000
    max-attempts: 3
  multithreading:
    num-threads: 2
  db:
    page-size: 10
  kafka:
    producer:
      binding-name-0: producer-out-0
      binding-name-1: producer-out-1
  scheduling:
    fixed-rate: 10000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/producerDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer 
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  cloud:
    stream:
      bindings:
        producer-out-1:
          destination: deposit-details
          producer:
            use-native-encoding: true
        producer-out-0:
          destination: test-product
          producer:
            use-native-encoding: true